#!/bin/bash

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Set Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
kill -s HUP $(cat /var/run/nginx.pid)

# Create HTML file containing the string "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html
