#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine nginx

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx start
