#!/usr/bin/env bash
# Configuring Nginx server so that /redirect_me is redirecting to another page.

# Update package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create HTML file containing the string "Holberton School"
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection using return with 301 status code
replacement="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/Skomaiya/;\n\t}"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

