#!/usr/bin/env bash
# Configuring Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Redirection config
replacement="server_name _;\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://github.com/Skomaiya/ permanent;\n\t}"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx start
