#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# Containing the string Ceci n'est pas une page

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create HTML file containing the string "Holberton School"
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection
replacement="server_name _;\n\trewrite ^/redirect_me https://github.com permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use custom 404 page
error_page_config="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen 80 default_server;|$error_page_config|" /etc/nginx/sites-available/default

# Test Nginx configuration and restart
sudo nginx -t
sudo service nginx restart

